/* SPDX-License-Identifier: Apache-2.0 */

#ifndef __ARCH_RISCV_SRC_COMPUKTER_HARDWARE_COMPUKTER_PLATFORM_H
#define __ARCH_RISCV_SRC_COMPUKTER_HARDWARE_COMPUKTER_PLATFORM_H

#define COMPUKTER_TIMER_MTIMECMP 0x10000200
#define COMPUKTER_TIMER_MTIME    0x10000208
#define COMPUKTER_TIMER_FREQUENCY 20

#define COMPUKTER_UART0_BASE 0x10001000
#define COMPUKTER_UART0_SOURCE 1

#endif
