/* SPDX-License-Identifier: Apache-2.0 */

#ifndef __ARCH_RISCV_SRC_COMPUKTER_HARDWARE_COMPUKTER_PLIC_H
#define __ARCH_RISCV_SRC_COMPUKTER_HARDWARE_COMPUKTER_PLIC_H

#define COMPUKTER_PLIC_BASE      0x0c000000
#define COMPUKTER_PLIC_PRIORITY  (COMPUKTER_PLIC_BASE + 0x000000)
#define COMPUKTER_PLIC_PENDING   (COMPUKTER_PLIC_BASE + 0x001000)
#define COMPUKTER_PLIC_ENABLE    (COMPUKTER_PLIC_BASE + 0x002000)
#define COMPUKTER_PLIC_THRESHOLD (COMPUKTER_PLIC_BASE + 0x200000)
#define COMPUKTER_PLIC_CLAIM     (COMPUKTER_PLIC_BASE + 0x200004)

#endif
